name: Koe
options:
  bundleIdPrefix: com.koe
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  Koe:
    type: application
    platform: macOS
    sources:
      - path: Koe
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.koe.app
        PRODUCT_NAME: Koe
        INFOPLIST_FILE: Koe/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Koe/Resources/Koe.entitlements
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: WhisperKit
    info:
      path: Koe/Resources/Info.plist
      properties:
        CFBundleName: Koe
        CFBundleDisplayName: "Koe - Voice Input"
        CFBundleIdentifier: com.koe.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: Koe
        LSUIElement: true
        LSMinimumSystemVersion: "14.0"
        NSMicrophoneUsageDescription: "Koe needs microphone access to record your voice for transcription."
